### PR TITLE
Adds a call to uvl_write for handling STDIN, STDOUT, and STDERR.

### PR DESCRIPTION
**Pull request by MrNetrix**

### CODE REVIEW

**Comment by xyzz** [comment]
Will merge once it's implemented in UVL. Aside, wouldn't it be better to have `uvl_log_write(char *buf, size_t size)` instead of `uvl_write(int fd, const void* buffer, u64_t size)`? Also here the last argument is of type size_t (32-bit) but in your UVL changes it's u64_t.

**Comment by MrNetrix** [comment]
I was thinking it might be useful to know if it's STDOUT, STDERR, etc. even though I don't currently make use of it. When I checked the typedef of size_t (with Intellisense), it showed the 64-bit version because of my 64-bit OS, so I'll fix it.

**Comment by xyzz** [comment]
It might be hard to make any use of that, unless you're writing to separate streams (stdout/stderr on the host or to different files). I think the logger should be as dumb as possible and simply output all data it receives to stdout, without inserting newlines or anything else. Since we're using a write-like API we don't know when it will actually be called, that depends on the buffer size and how it's flushed. For example it's entirely possible for printf("Hello world!") to be sent as write("Hello ") write("world!") and we don't want to see any newlines Vita didn't send (the current logger has this problem so we see a lot of duplicated newlines).

**Comment by MrNetrix** [comment]
Well if you look at yifanlu's recent changes to VitaDefiler, he made
different streams for stdout and stderr, so it's possible to make use of
that. As for newlines, I find it's easier to read the output with the extra
newlines, but that can be up to devs to decide how many to put. I'm
accounting for situations like you mentioned.

**Comment by xyzz** [comment]
Merged as a part of #6

**Pull request closed without merging**
